#pragma once

#include "ayu/data/ayu_database.h"
#include "ayu/data/entities.h"
#include "ayu/features/teleforge/teleforge_storage.h"
#include "ayu/features/teleforge/tf_peer_archive_entities.h"
#include "ayu/libs/sqlite/sqlite_orm.h"

namespace TeleForge::Storage {

using namespace sqlite_orm;

[[nodiscard]] inline auto MakeUnifiedStorage(std::string dbPath) {
	// sqlite_orm::sync_schema iterates db_objects in reverse order;
	// indexes must appear before their tables in this list.
	return make_storage(
		std::move(dbPath),
		make_index(
			"idx_sync_artifact_type_updated",
			column<SyncArtifactRecord>(&SyncArtifactRecord::artifactType),
			column<SyncArtifactRecord>(&SyncArtifactRecord::updatedAt)),
		make_index(
			"idx_memory_scope_lookup",
			column<MemoryItemRecord>(&MemoryItemRecord::scopeType),
			column<MemoryItemRecord>(&MemoryItemRecord::chatId),
			column<MemoryItemRecord>(&MemoryItemRecord::userId),
			column<MemoryItemRecord>(&MemoryItemRecord::manualHidden)),
		make_index(
			"idx_memory_access",
			column<MemoryItemRecord>(&MemoryItemRecord::lastAccessAt),
			column<MemoryItemRecord>(&MemoryItemRecord::updatedAt)),
		make_index(
			"idx_memory_sync_pending",
			column<MemorySyncEventRecord>(&MemorySyncEventRecord::dispatchedAt),
			column<MemorySyncEventRecord>(&MemorySyncEventRecord::createdAt)),
		make_index(
			"idx_deleted_message_userId_dialogId_topicId_messageId",
			column<DeletedMessage>(&DeletedMessage::userId),
			column<DeletedMessage>(&DeletedMessage::dialogId),
			column<DeletedMessage>(&DeletedMessage::topicId),
			column<DeletedMessage>(&DeletedMessage::messageId)),
		make_index(
			"idx_edited_message_userId_dialogId_messageId",
			column<EditedMessage>(&EditedMessage::userId),
			column<EditedMessage>(&EditedMessage::dialogId),
			column<EditedMessage>(&EditedMessage::messageId)),
		make_index(
			"idx_deleted_message_contentHash",
			column<DeletedMessage>(&DeletedMessage::contentHash)),
		make_index(
			"idx_edited_message_contentHash",
			column<EditedMessage>(&EditedMessage::contentHash)),
		make_index(
			"idx_online_event_userId_timestamp",
			column<OnlineEvent>(&OnlineEvent::userId),
			column<OnlineEvent>(&OnlineEvent::timestamp)),
		make_index(
			"idx_peer_archive_username_peer",
			column<PeerArchive::UsernameRecord>(&PeerArchive::UsernameRecord::peerId),
			column<PeerArchive::UsernameRecord>(&PeerArchive::UsernameRecord::observedAt)),
		make_index(
			"idx_peer_archive_chat_peer",
			column<PeerArchive::ChatMembershipRecord>(&PeerArchive::ChatMembershipRecord::peerId),
			column<PeerArchive::ChatMembershipRecord>(&PeerArchive::ChatMembershipRecord::chatId)),
		make_table<SchemaVersionRecord>(
			"SchemaVersion",
			make_column("singletonId", &SchemaVersionRecord::singletonId, primary_key()),
			make_column("version", &SchemaVersionRecord::version)),
		make_table<AyuDataSchemaVersion>(
			"AyuDataSchemaVersion",
			make_column("id", &AyuDataSchemaVersion::id, primary_key()),
			make_column("version", &AyuDataSchemaVersion::version)),
		make_table<PersonalityCoreRecord>(
			"PersonalityCore",
			make_column("singletonId", &PersonalityCoreRecord::singletonId, primary_key()),
			make_column("aggression", &PersonalityCoreRecord::aggression),
			make_column("brevity", &PersonalityCoreRecord::brevity),
			make_column("emojis", &PersonalityCoreRecord::emojis),
			make_column("toxicity", &PersonalityCoreRecord::toxicity),
			make_column("creativity", &PersonalityCoreRecord::creativity),
			make_column("systemPrompt", &PersonalityCoreRecord::systemPrompt),
			make_column("sourceDevice", &PersonalityCoreRecord::sourceDevice),
			make_column("updatedAt", &PersonalityCoreRecord::updatedAt),
			make_column("embeddingEndpointUrl", &PersonalityCoreRecord::embeddingEndpointUrl),
			make_column("embeddingModelId", &PersonalityCoreRecord::embeddingModelId),
			make_column("lmStudioBaseUrl", &PersonalityCoreRecord::lmStudioBaseUrl),
			make_column("chatModelPath", &PersonalityCoreRecord::chatModelPath),
			make_column("chatModelId", &PersonalityCoreRecord::chatModelId),
			make_column("openAiApiKey", &PersonalityCoreRecord::openAiApiKey),
			make_column("chatContextMessages", &PersonalityCoreRecord::chatContextMessages),
			make_column("memorySyncEnabled", &PersonalityCoreRecord::memorySyncEnabled),
			make_column("rerankEndpointUrl", &PersonalityCoreRecord::rerankEndpointUrl),
			make_column("rerankModelId", &PersonalityCoreRecord::rerankModelId),
			make_column("rerankModelPath", &PersonalityCoreRecord::rerankModelPath),
			make_column("autoSendEnabled", &PersonalityCoreRecord::autoSendEnabled),
			make_column("visionEnabled", &PersonalityCoreRecord::visionEnabled),
			make_column("cloudBackend", &PersonalityCoreRecord::cloudBackend),
			make_column("pgConnString", &PersonalityCoreRecord::pgConnString),
			make_column("pgVersion", &PersonalityCoreRecord::pgVersion)),
		make_table<PerChatSettingsRecord>(
			"PerChatSettings",
			make_column("peerId", &PerChatSettingsRecord::peerId, primary_key()),
			make_column("aiAnswer", &PerChatSettingsRecord::aiAnswer),
			make_column("webAccess", &PerChatSettingsRecord::webAccess),
			make_column("calendarAccess", &PerChatSettingsRecord::calendarAccess),
			make_column("pcAgent", &PerChatSettingsRecord::pcAgent),
			make_column("memoryReadEnabled", &PerChatSettingsRecord::memoryReadEnabled),
			make_column("memoryWriteEnabled", &PerChatSettingsRecord::memoryWriteEnabled),
			make_column("globalMemoryTopK", &PerChatSettingsRecord::globalMemoryTopK),
			make_column("chatMemoryTopK", &PerChatSettingsRecord::chatMemoryTopK),
			make_column("userMemoryTopK", &PerChatSettingsRecord::userMemoryTopK),
			make_column("memoryAppendixTopK", &PerChatSettingsRecord::memoryAppendixTopK),
			make_column("recentSummaryLimit", &PerChatSettingsRecord::recentSummaryLimit),
			make_column("stableFactsLimit", &PerChatSettingsRecord::stableFactsLimit),
			make_column("memoryDecayPerDay", &PerChatSettingsRecord::memoryDecayPerDay),
			make_column("directoryWhitelistJson", &PerChatSettingsRecord::directoryWhitelistJson),
			make_column("maxMemoryBlockChars", &PerChatSettingsRecord::maxMemoryBlockChars),
			make_column("updatedAt", &PerChatSettingsRecord::updatedAt)),
		make_table<MemoryItemRecord>(
			"MemoryItem",
			make_column("id", &MemoryItemRecord::id, primary_key().autoincrement()),
			make_column("scopeType", &MemoryItemRecord::scopeType),
			make_column("chatId", &MemoryItemRecord::chatId),
			make_column("userId", &MemoryItemRecord::userId),
			make_column("sourcePeerId", &MemoryItemRecord::sourcePeerId),
			make_column("sourceMessageId", &MemoryItemRecord::sourceMessageId),
			make_column("title", &MemoryItemRecord::title),
			make_column("summary", &MemoryItemRecord::summary),
			make_column("details", &MemoryItemRecord::details),
			make_column("factType", &MemoryItemRecord::factType),
			make_column("tagsJson", &MemoryItemRecord::tagsJson),
			make_column("basePriority", &MemoryItemRecord::basePriority),
			make_column("stabilityScore", &MemoryItemRecord::stabilityScore),
			make_column("createdAt", &MemoryItemRecord::createdAt),
			make_column("updatedAt", &MemoryItemRecord::updatedAt),
			make_column("lastAccessAt", &MemoryItemRecord::lastAccessAt),
			make_column("accessCount", &MemoryItemRecord::accessCount),
			make_column("manualPinned", &MemoryItemRecord::manualPinned),
			make_column("manualHidden", &MemoryItemRecord::manualHidden),
			make_column("syncState", &MemoryItemRecord::syncState),
			make_column("contentHash", &MemoryItemRecord::contentHash)),
		make_table<MemoryEmbeddingRecord>(
			"MemoryEmbedding",
			make_column("memoryId", &MemoryEmbeddingRecord::memoryId, primary_key()),
			make_column("modelId", &MemoryEmbeddingRecord::modelId),
			make_column("dimensions", &MemoryEmbeddingRecord::dimensions),
			make_column("vectorBlob", &MemoryEmbeddingRecord::vectorBlob),
			make_column("createdAt", &MemoryEmbeddingRecord::createdAt),
			make_column("updatedAt", &MemoryEmbeddingRecord::updatedAt)),
		make_table<MemorySyncEventRecord>(
			"MemorySyncEvent",
			make_column("id", &MemorySyncEventRecord::id, primary_key().autoincrement()),
			make_column("eventType", &MemorySyncEventRecord::eventType),
			make_column("memoryId", &MemorySyncEventRecord::memoryId),
			make_column("payload", &MemorySyncEventRecord::payload),
			make_column("deviceId", &MemorySyncEventRecord::deviceId),
			make_column("createdAt", &MemorySyncEventRecord::createdAt),
			make_column("dispatchedAt", &MemorySyncEventRecord::dispatchedAt)),
		make_table<SyncArtifactRecord>(
			"SyncArtifact",
			make_column("id", &SyncArtifactRecord::id, primary_key().autoincrement()),
			make_column("artifactType", &SyncArtifactRecord::artifactType),
			make_column("artifactName", &SyncArtifactRecord::artifactName),
			make_column("payload", &SyncArtifactRecord::payload),
			make_column("deviceId", &SyncArtifactRecord::deviceId),
			make_column("updatedAt", &SyncArtifactRecord::updatedAt)),
		make_table<DeletedMessage>(
			"DeletedMessage",
			make_column("fakeId", &DeletedMessage::fakeId, primary_key().autoincrement()),
			make_column("userId", &DeletedMessage::userId),
			make_column("dialogId", &DeletedMessage::dialogId),
			make_column("groupedId", &DeletedMessage::groupedId),
			make_column("peerId", &DeletedMessage::peerId),
			make_column("fromId", &DeletedMessage::fromId),
			make_column("topicId", &DeletedMessage::topicId),
			make_column("messageId", &DeletedMessage::messageId),
			make_column("date", &DeletedMessage::date),
			make_column("flags", &DeletedMessage::flags),
			make_column("editDate", &DeletedMessage::editDate),
			make_column("views", &DeletedMessage::views),
			make_column("fwdFlags", &DeletedMessage::fwdFlags),
			make_column("fwdFromId", &DeletedMessage::fwdFromId),
			make_column("fwdName", &DeletedMessage::fwdName),
			make_column("fwdDate", &DeletedMessage::fwdDate),
			make_column("fwdPostAuthor", &DeletedMessage::fwdPostAuthor),
			make_column("replyFlags", &DeletedMessage::replyFlags),
			make_column("replyMessageId", &DeletedMessage::replyMessageId),
			make_column("replyPeerId", &DeletedMessage::replyPeerId),
			make_column("replyTopId", &DeletedMessage::replyTopId),
			make_column("replyForumTopic", &DeletedMessage::replyForumTopic),
			make_column("replySerialized", &DeletedMessage::replySerialized),
			make_column("entityCreateDate", &DeletedMessage::entityCreateDate),
			make_column("text", &DeletedMessage::text),
			make_column("textEntities", &DeletedMessage::textEntities),
			make_column("mediaPath", &DeletedMessage::mediaPath),
			make_column("hqThumbPath", &DeletedMessage::hqThumbPath),
			make_column("documentType", &DeletedMessage::documentType),
			make_column("documentSerialized", &DeletedMessage::documentSerialized),
			make_column("thumbsSerialized", &DeletedMessage::thumbsSerialized),
			make_column("documentAttributesSerialized", &DeletedMessage::documentAttributesSerialized),
			make_column("mimeType", &DeletedMessage::mimeType),
			make_column("contentHash", &DeletedMessage::contentHash)),
		make_table<EditedMessage>(
			"EditedMessage",
			make_column("fakeId", &EditedMessage::fakeId, primary_key().autoincrement()),
			make_column("userId", &EditedMessage::userId),
			make_column("dialogId", &EditedMessage::dialogId),
			make_column("groupedId", &EditedMessage::groupedId),
			make_column("peerId", &EditedMessage::peerId),
			make_column("fromId", &EditedMessage::fromId),
			make_column("topicId", &EditedMessage::topicId),
			make_column("messageId", &EditedMessage::messageId),
			make_column("date", &EditedMessage::date),
			make_column("flags", &EditedMessage::flags),
			make_column("editDate", &EditedMessage::editDate),
			make_column("views", &EditedMessage::views),
			make_column("fwdFlags", &EditedMessage::fwdFlags),
			make_column("fwdFromId", &EditedMessage::fwdFromId),
			make_column("fwdName", &EditedMessage::fwdName),
			make_column("fwdDate", &EditedMessage::fwdDate),
			make_column("fwdPostAuthor", &EditedMessage::fwdPostAuthor),
			make_column("replyFlags", &EditedMessage::replyFlags),
			make_column("replyMessageId", &EditedMessage::replyMessageId),
			make_column("replyPeerId", &EditedMessage::replyPeerId),
			make_column("replyTopId", &EditedMessage::replyTopId),
			make_column("replyForumTopic", &EditedMessage::replyForumTopic),
			make_column("replySerialized", &EditedMessage::replySerialized),
			make_column("entityCreateDate", &EditedMessage::entityCreateDate),
			make_column("text", &EditedMessage::text),
			make_column("textEntities", &EditedMessage::textEntities),
			make_column("mediaPath", &EditedMessage::mediaPath),
			make_column("hqThumbPath", &EditedMessage::hqThumbPath),
			make_column("documentType", &EditedMessage::documentType),
			make_column("documentSerialized", &EditedMessage::documentSerialized),
			make_column("thumbsSerialized", &EditedMessage::thumbsSerialized),
			make_column("documentAttributesSerialized", &EditedMessage::documentAttributesSerialized),
			make_column("mimeType", &EditedMessage::mimeType),
			make_column("contentHash", &EditedMessage::contentHash)),
		make_table<DeletedDialog>(
			"DeletedDialog",
			make_column("fakeId", &DeletedDialog::fakeId, primary_key().autoincrement()),
			make_column("userId", &DeletedDialog::userId),
			make_column("dialogId", &DeletedDialog::dialogId),
			make_column("peerId", &DeletedDialog::peerId),
			make_column("folderId", &DeletedDialog::folderId),
			make_column("topMessage", &DeletedDialog::topMessage),
			make_column("lastMessageDate", &DeletedDialog::lastMessageDate),
			make_column("flags", &DeletedDialog::flags),
			make_column("entityCreateDate", &DeletedDialog::entityCreateDate)),
		make_table<RegexFilter>(
			"RegexFilter",
			make_column("id", &RegexFilter::id, primary_key()),
			make_column("text", &RegexFilter::text),
			make_column("enabled", &RegexFilter::enabled),
			make_column("reversed", &RegexFilter::reversed),
			make_column("caseInsensitive", &RegexFilter::caseInsensitive),
			make_column("dialogId", &RegexFilter::dialogId)),
		make_table<RegexFilterGlobalExclusion>(
			"RegexFilterGlobalExclusion",
			make_column("fakeId", &RegexFilterGlobalExclusion::fakeId, primary_key().autoincrement()),
			make_column("dialogId", &RegexFilterGlobalExclusion::dialogId),
			make_column("filterId", &RegexFilterGlobalExclusion::filterId)),
		make_table<SpyMessageRead>(
			"SpyMessageRead",
			make_column("fakeId", &SpyMessageRead::fakeId, primary_key().autoincrement()),
			make_column("userId", &SpyMessageRead::userId),
			make_column("dialogId", &SpyMessageRead::dialogId),
			make_column("messageId", &SpyMessageRead::messageId),
			make_column("entityCreateDate", &SpyMessageRead::entityCreateDate)),
		make_table<SpyMessageContentsRead>(
			"SpyMessageContentsRead",
			make_column("fakeId", &SpyMessageContentsRead::fakeId, primary_key().autoincrement()),
			make_column("userId", &SpyMessageContentsRead::userId),
			make_column("dialogId", &SpyMessageContentsRead::dialogId),
			make_column("messageId", &SpyMessageContentsRead::messageId),
			make_column("entityCreateDate", &SpyMessageContentsRead::entityCreateDate)),
		make_table<OnlineEvent>(
			"OnlineEvent",
			make_column("fakeId", &OnlineEvent::fakeId, primary_key().autoincrement()),
			make_column("userId", &OnlineEvent::userId),
			make_column("timestamp", &OnlineEvent::timestamp),
			make_column("kind", &OnlineEvent::kind),
			make_column("onlineTill", &OnlineEvent::onlineTill),
			make_column("manualLastSeen", &OnlineEvent::manualLastSeen)),
		make_table<SpyTarget>(
			"SpyTarget",
			make_column("userId", &SpyTarget::userId, primary_key()),
			make_column("enabled", &SpyTarget::enabled),
			make_column("since", &SpyTarget::since)),
		make_table<PeerArchive::ProfileRecord>(
			"PeerArchiveProfile",
			make_column("peerId", &PeerArchive::ProfileRecord::peerId, primary_key()),
			make_column("firstSeenAt", &PeerArchive::ProfileRecord::firstSeenAt),
			make_column("lastSeenAt", &PeerArchive::ProfileRecord::lastSeenAt),
			make_column("firstChatId", &PeerArchive::ProfileRecord::firstChatId),
			make_column("firstMessageId", &PeerArchive::ProfileRecord::firstMessageId),
			make_column("firstSource", &PeerArchive::ProfileRecord::firstSource)),
		make_table<PeerArchive::UsernameRecord>(
			"PeerArchiveUsername",
			make_column("id", &PeerArchive::UsernameRecord::id, primary_key().autoincrement()),
			make_column("peerId", &PeerArchive::UsernameRecord::peerId),
			make_column("username", &PeerArchive::UsernameRecord::username),
			make_column("observedAt", &PeerArchive::UsernameRecord::observedAt)),
		make_table<PeerArchive::NameRecord>(
			"PeerArchiveName",
			make_column("id", &PeerArchive::NameRecord::id, primary_key().autoincrement()),
			make_column("peerId", &PeerArchive::NameRecord::peerId),
			make_column("firstName", &PeerArchive::NameRecord::firstName),
			make_column("lastName", &PeerArchive::NameRecord::lastName),
			make_column("observedAt", &PeerArchive::NameRecord::observedAt)),
		make_table<PeerArchive::BioRecord>(
			"PeerArchiveBio",
			make_column("id", &PeerArchive::BioRecord::id, primary_key().autoincrement()),
			make_column("peerId", &PeerArchive::BioRecord::peerId),
			make_column("bio", &PeerArchive::BioRecord::bio),
			make_column("observedAt", &PeerArchive::BioRecord::observedAt)),
		make_table<PeerArchive::UserpicRecord>(
			"PeerArchiveUserpic",
			make_column("id", &PeerArchive::UserpicRecord::id, primary_key().autoincrement()),
			make_column("peerId", &PeerArchive::UserpicRecord::peerId),
			make_column("localPath", &PeerArchive::UserpicRecord::localPath),
			make_column("observedAt", &PeerArchive::UserpicRecord::observedAt),
			make_column("photoId", &PeerArchive::UserpicRecord::photoId)),
		make_table<PeerArchive::ChatMembershipRecord>(
			"PeerArchiveChatMembership",
			make_column("id", &PeerArchive::ChatMembershipRecord::id, primary_key().autoincrement()),
			make_column("peerId", &PeerArchive::ChatMembershipRecord::peerId),
			make_column("chatId", &PeerArchive::ChatMembershipRecord::chatId),
			make_column("chatTitle", &PeerArchive::ChatMembershipRecord::chatTitle),
			make_column("firstSeenAt", &PeerArchive::ChatMembershipRecord::firstSeenAt),
			make_column("lastSeenAt", &PeerArchive::ChatMembershipRecord::lastSeenAt),
			make_column("selfInChat", &PeerArchive::ChatMembershipRecord::selfInChat),
			make_column("peerStillInChat", &PeerArchive::ChatMembershipRecord::peerStillInChat)));
}

using UnifiedStorage = decltype(MakeUnifiedStorage(std::string{}));

UnifiedStorage &Db();

} // namespace TeleForge::Storage
